# Generated by Django 4.2.1 on 2023-05-27 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_bankuser_branch'),
        ('bills', '0002_accountbills_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountbills',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UserBills', to='users.bankuser'),
        ),
    ]
