# Generated by Django 4.2.1 on 2023-05-27 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0003_alter_accountbills_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountbills',
            name='user',
        ),
    ]
