# Generated by Django 4.2.1 on 2023-05-27 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0004_remove_accountbills_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountbills',
            name='remark',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='accountbills',
            name='type',
            field=models.CharField(choices=[('收入', '收入'), ('支出', '支出')], default='收入', max_length=100),
        ),
    ]
