# Generated by Django 4.2.1 on 2023-05-27 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0006_accountbills_money'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountbills',
            name='remark',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
