# Generated by Django 4.2.1 on 2023-06-01 01:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branch', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchDepartments',
            fields=[
                ('department_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=1000)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='BranchDepartments', to='branch.bankbranch')),
            ],
        ),
    ]
