# Generated by Django 4.2.1 on 2023-06-01 11:50

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0010_alter_bankuser_branch'),
        ('branch', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loans',
            fields=[
                ('loan_id', models.AutoField(primary_key=True, serialize=False)),
                ('money', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('loan_date', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateTimeField(default=datetime.datetime(2024, 5, 31, 19, 50, 16, 743625))),
                ('status', models.CharField(choices=[('未还清', '未还清'), ('已还清', '已还清')], default='未还清', max_length=100)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='BranchLoans', to='branch.bankbranch')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UserLoans', to='users.bankuser')),
            ],
        ),
    ]
