# Generated by Django 4.2.1 on 2023-06-01 12:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loans',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 31, 20, 6, 50, 58788)),
        ),
    ]
