# Generated by Django 4.2.1 on 2023-06-01 13:29

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_alter_loans_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='loans',
            name='remain_money',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='loans',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 31, 21, 29, 36, 22121)),
        ),
    ]
