# Generated by Django 4.2.1 on 2023-05-27 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankBranch',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=100)),
                ('tel', models.CharField(max_length=11)),
            ],
        ),
    ]
