# Generated by Django 4.2.1 on 2023-05-27 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0001_initial'),
        ('accounts', '0002_remove_useraccounts_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccounts',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='BranchAccounts', to='branch.bankbranch'),
        ),
    ]
