# Generated by Django 4.2.1 on 2023-05-27 08:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_useraccounts_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccounts',
            name='money',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
