# Generated by Django 4.2.1 on 2023-06-01 02:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branch', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('staff_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('tel', models.CharField(max_length=11)),
                ('address', models.CharField(max_length=100)),
                ('photo', models.ImageField(default='photos/default.png', upload_to='photos/%Y%m%d/')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='BranchStaff', to='branch.bankbranch')),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('staff', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='StaffManager', serialize=False, to='staffs.staff')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='BranchManager', to='branch.bankbranch')),
            ],
        ),
    ]
