# Generated by Django 4.2.1 on 2023-06-01 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='photo',
            field=models.ImageField(default='photos/20230601/default.png', upload_to='photos/%Y%m%d/'),
        ),
    ]
