# Generated by Django 4.2.1 on 2023-06-01 02:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0001_initial'),
        ('staffs', '0002_alter_staff_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manager',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='branch',
        ),
        migrations.AddField(
            model_name='manager',
            name='department',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='DepartmentManager', to='department.branchdepartments'),
        ),
        migrations.AddField(
            model_name='staff',
            name='department',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='DepartmentStaff', to='department.branchdepartments'),
        ),
    ]
