# Generated by Django 4.2.1 on 2023-06-01 02:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0001_initial'),
        ('staffs', '0003_remove_manager_branch_remove_staff_branch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DepartmentManager', to='department.branchdepartments'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DepartmentStaff', to='department.branchdepartments'),
        ),
    ]
