# Generated by Django 4.2.1 on 2023-05-27 01:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0006_bankuser_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankuser',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='BankUser', to=settings.AUTH_USER_MODEL),
        ),
    ]
