# Generated by Django 4.2.1 on 2023-05-27 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0001_initial'),
        ('users', '0008_bankuser_counts_bankuser_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankuser',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='BankBranch', to='branch.bankbranch'),
        ),
    ]
